HELP
====

This is a pre-release version with little documentation, but neither should much documentation be needed. If you are
familiar for the basic UNIX command-line utilities such as +cp+, +mv+, +mkdir+ and +cat+ then this will be easy to use.
Most of the command-line options from the GNU versions of these utilities are supported.

Assuming that you have unpack the distribution to a directory called VFSDIR then set +PATH+ to include +VFSDIR/bin+.

Run +vfs --help+ for a basic help page or to get command-specific help run something like +vfs cp --help+ or
+vfs mv --help+.

Run +vfs --list-schemes+ to get a list of supported schemes.

Groovy VFS urls are supported. You can do something like +vfs cp 'ftp://some.server/pub/file.txt?vfs.ftp.passiveMode=1'
'sftp://another.server/tmp?vfs.sftp.userDirIsRoot=0'+. For more options see the Groovy VFS wiki - https://github.com/ysb33r/groovy-vfs/wiki/Protocol-Options

Please raise defects on GitHub - https://github.com/ysb33r/groovy-vfs/issues?state=open

